ALTER TABLE `s_sms` ADD `brand` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `s_sms` ADD `model` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `s_sms` ADD `simcartserial` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `s_sms` ADD `smsmessageid` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `s_sms` ADD `userdata` VARCHAR(100) NULL DEFAULT NULL;
