ALTER TABLE `needs` ADD `allowpirce` BIT(1) NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `iactive` BIT(1) NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `price1` INT(10) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `price2` INT(10) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `price3` INT(10) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `title1` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `title2` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `needs` ADD `title3` VARCHAR(100) NULL DEFAULT NULL;